### ISSUE TITLE
Recognize multiple QR

### ISSUE THREAD

**Issue by markusand** [cageehv/zxing4processing#1]
Could it be possible to detect more than one QR code in one image (or webcam stream)?

**Comment by cageehv** [comment]
Hey markusand,

Thanks for the feedback!

I released version 3.3 of the library and added a new method:
decodeMultipleQRCodes()
That will decode one or more QR codes in an PImage.

Enjoy!

peace,
Rolf

**Comment by luk-p** [comment]
Hi Rolf, thanks a lot for your helpful library!
I noticed that `getPositionMarkers(int index)` does not update like `getPositionMarkers()` does. I edited the example „decodeMultipleCodes“ to use with a video stream. The several codes do get detected but their location stay at the initial value when the sketch was started.
Am I missing something?

**Comment by cageehv** [comment]
Hey Luk,

Thanks for the kudos!

Can you please send me a copy of your modified decodeMultipleCodes sketch, so I can see the problem?
(mail: info@cagewebdev.com)

Thanks!
Rolf

**Comment by cageehv** [comment]
Hey Luk,

I fixed the bug and released v3.4.
See:
http://cagewebdev.com/zxing4processing-processing-library/

peace,
Rolf

**Comment by luk-p** [comment]
Amazing, it works like a treat!
Thank you!
Luk
